### ISSUE TITLE
Back Button

### ISSUE THREAD

**Issue by kabradshaw1** [bslockhart/Group-Project-1#2]
*Back Button*

- Freeze the header
- Logo at top return to index.html

**Comment by jrargent** [comment]
My worry is having the link at the top act as the back button will not be intuitive to users. 

My opinion is that having a clearly defined back button would be better from a user perspective. 

I am also happy to take on this issue and do a draft to show what I mean.

**Comment by jrargent** [comment]
I have completed this feature and added a pull request. I will close this issue when the pull request is approved.
