### ISSUE TITLE
Clean up footer.

### ISSUE THREAD

**Issue by bslockhart** [bslockhart/Group-Project-1#20]
Make the content in the footer look good.

**Comment by August-Lascola** [comment]
![image](https://user-images.githubusercontent.com/109111489/188980746-bffdebcc-a97d-40bc-ac07-d38240b5c5c1.png)

Made font size smaller + added text shadow to footer title. Working on organizing our names better

**Comment by August-Lascola** [comment]
Also Brian, your github link directed the user to the project repo... I assume you want it changed to your profile?

**Comment by bslockhart** [comment]
Looks Awesome...
